### ISSUE TITLE
Provide Examples to Support Multiple Unsecured Operations

### ISSUE THREAD

**Issue by pipebaum** [innoventsolutions/BIRT-Report-Runner-REST-Service#14]
If a user would like to have multiple unsecured operations (e.g. status, status-all, job, and jobs) what would be the appropriate pattern to allow all of those?

Are multiple operations allowed in this config?

**Comment by SteveSchafer-Innovent** [comment]
You can use a regular expression that will match multiple things, such as

birt.runner.unsecuredOperationPattern=status|status-all|job|jobs

Added example to readme.MD.

**Comment by pipebaum** [comment]
Easy enough, and it works.
